indent_width = 4
column_width = 120
indent_type = "Spaces"

quote_style = "ForceDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never" # Never, FunctionOnly, ConditionalOnly, or Always
line_endings = "Unix"
